### ISSUE TITLE
JsCallback of showScanQrPopup returns [object Object] instead of QR string result

### ISSUE THREAD

**Issue by TerehinAV** [rohitsangwan01/flutter_telegram_web_app#1]
How to get QR string from data param in JsCallback?
As deep as I could dive - data is minified Q object and have no thoughts how to get string from it

The code below (which has taken from example and a little bit modified) leads to this:
![telegram-cloud-photo-size-2-5348490884032877701-y](https://github.com/rohitsangwan01/flutter_telegram_web_app/assets/13195377/2109ea15-82ee-4eb5-b68b-0900cab9819e)

```

import 'package:flutter/material.dart';

import 'common_widgets.dart';
import 'package:flutter_telegram_web_app/flutter_telegram_web_app.dart' as tg;
import 'package:flutter_telegram_web_app/flutter_telegram_web_app.dart';
import 'main.dart';

class HomeView extends StatefulWidget {
  const HomeView({super.key});

  @override
  State<HomeView> createState() => _HomeViewState();
}

class _HomeViewState extends State<HomeView> {
  String? qrText = "No QR yet...";
  bool isStateStable = true;

  @override
  void initState() {
    onEvent(TelegramWebEventType.qrTextReceived, JsCallback<dynamic>((data) {
      String text = '';
      try {
        text = "${data?.toString() ?? 'data is null'} of type  ${data
            ?.runtimeType ?? ''}";
      } catch (e) {
        text = "Error: $e {$data}";
      }
      showAlert(text);
      qrText = text;
      setState(() {});
      tg.closeScanQrPopup();
    }));

    TelegramWebEvent.setThemeChangeListener(
        (bool isDarkMode, ThemeParams themeParams) {
      setState(() {});
      updateThemeMode();
    });

    TelegramWebEvent.setViewPortChangeListener(
        (bool isStable, height, stableHeight) {
      setState(() {
        isStateStable = isStable;
      });
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body:
        Center(
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(qrText ?? 'No QR yet...'),
                  KButton(
                      text: "Open QR Scanner",
                      onTap: () => tg.showScanQrPopup((
                                  text: "Scan QR",
                                  JsCallback<dynamic>((data) {
                              showAlert("${data?.toString() ?? 'data is null'} of type  ${data?.runtimeType ?? ''}");
                              qrText = "${data?.toString() ?? 'data is null'} of type  ${data?.runtimeType ?? ''}";
                              tg.closeScanQrPopup();
                              })
                          ))
                  )
                  ])
      )
    );
  }
}

```

Any ideas could help.

**Comment by TerehinAV** [comment]
UPD
After a bit googling I've found that JsCallback should return an object ('event') with 'data' field. 
When I tried to get `data?.data`:


```
@override
  void initState() {
    onEvent(TelegramWebEventType.qrTextReceived, JsCallback<dynamic>((data) {
      String text = '';
      try {
        text = "${data?.data ?? 'data is null'} of type  ${data
            ?.runtimeType ?? ''}";
      } catch (e) {
        text = "Error: $e {$data}";
      }
      showAlert(text);
      qrText = text;
      setState(() {});
      tg.closeScanQrPopup();
    }));
```

I've got an error:
![telegram-cloud-photo-size-2-5357272314036739839-y](https://github.com/rohitsangwan01/flutter_telegram_web_app/assets/13195377/de61ec4b-1052-4afe-a60f-1582226f68ae)

**Comment by rohitsangwan01** [comment]
@TerehinAV i think the callback from javascript will return something like `{ data: 'RESULT' }`, so we need to create a listener of this type
but your approach also seems to be good, a dynamic object passed as `data` and access with `data.data`
i am also using same approach [here](https://github.com/rohitsangwan01/flutter_telegram_web_app/blob/main/lib/src/helpers/telegram_web_events.dart#L11-L16)
can you cross check if this `setViewPortChangeListener`  is working for you ?



or maybe try to create a js object like this

```dart
import 'package:js/js.dart';

@JS()
class TelegramQrResult {
  external String? data;
}

JsCallback<TelegramQrResult>((data){})
```

**Comment by TerehinAV** [comment]
> ```dart
> import 'package:js/js.dart';
> 
> @JS()
> class TelegramQrResult {
>   external String? data;
> }
> 
> JsCallback<TelegramQrResult>((data){})
> ```

Thank you! That helped. 
Please add this part into an example. I guess I'm not only one who faced this issue)

p.s. A little offtop question: is it possible to call showScanQrPopup directly after app's start without special button click?

**Comment by rohitsangwan01** [comment]
@TerehinAV Great, i will add in docs later with any update maybe
not really checked the qr related part, so can't say, you can check in Telegram's documents if this is possible
